### ISSUE TITLE
automate=false doesn't work

### ISSUE THREAD

**Issue by sennewood** [toddharrison/PlayerState#2]
In the PlayerState.cfg I set automate=false, but after I joined my Server it seems to be active:

[16:41:01] [net.minecraft.server.MinecraftServer] [INFO]: Sen joined the game
[16:41:17] [PlayerState] [INFO]: Saved Sen at state WORLD_ALL
[16:41:17] [PlayerState] [INFO]: Loaded Sen at state WORLD_ALL: true

**Comment by toddharrison** [comment]
I will look into this, that could be expected behavior but I will make sure. The `WORLD_ALL` represents your common configuration outside of any one world, so I believe it is suppose to work that way. I would need to be able to restore to `WORLD_ALL` whenever you leave a world that is specifically managed, say through the PlayerState API.

**Comment by toddharrison** [comment]
On review, this works as it should. The `automate` property governs how PlayerState manages worlds automatically. When it it true, it will save the state for each world independent of other worlds. When it is false, it will save a global worlds state `WORLD_ALL`. I need this global worlds state so that I can revert to it when a player leaves a world registered through the PlayerState API. Please let me know if you have questions or if this causes you a problem and I'll investigate, thanks.

**Comment by sennewood** [comment]
Means this, that all lines with ";" are no comments? Because all WORLD_ALL values begin with it.

**Comment by toddharrison** [comment]
Right, those are comments. I believe they were in there as examples. Without documentation I think they're just confusing though so I'll take them out and provide some documentation on the configuration in that file. Will that help?

**Comment by sennewood** [comment]
Documentation always helps :)
There or in the readme.
